import Link from 'next/link';
import { ProductCard } from '../components/product-card';
import { getProducts } from '../lib/products';

export const dynamic = 'force-dynamic';

export default async function Home() {
  const homeProducts = await getProducts({ homepage: true });
  const featured = homeProducts.filter(product => product.is_featured);
  const newest = homeProducts.filter(product => product.is_new);
  return <main><section className="hero"><div className="hero-copy"><span className="eyebrow light">✳ &nbsp; THE LITTLE EXPLORERS CLUB</span><h1>Petualangan<br />dimulai dari<br /><em>langkah kecil.</em></h1><p>Temukan teman bermain di luar ruang untuk si kecil yang selalu ingin tahu.</p><Link href="/shop" className="button light-button">Jelajahi koleksi <span>↗</span></Link></div><div className="hero-stamp">MADE FOR<br />LITTLE<br />ADVENTURES <span>✳</span></div></section><div className="promise-bar"><span>✳ &nbsp; SIAP UNTUK PETUALANGAN</span><span>✳ &nbsp; PILIHAN UNTUK ANAK AKTIF</span><span>✳ &nbsp; BELANJA MUDAH & AMAN</span></div><section className="section"><div className="section-head"><div><span className="eyebrow">PILIHAN FAVORIT</span><h2>Best Seller<span className="orange-dot">.</span></h2></div><Link href="/shop" className="text-link">Lihat semua <span>↗</span></Link></div><div className="product-grid">{featured.map(product => <ProductCard key={product.id} product={product} />)}</div></section><section className="story-band"><div><span className="eyebrow light">LET THEM EXPLORE</span><h2>Lebih banyak<br />bermain di luar.</h2><p>Hari yang seru dimulai dengan rasa ingin tahu. Pilih perlengkapan yang siap ikut ke mana saja.</p><Link href="/shop" className="button light-button">Belanja sekarang <span>↗</span></Link></div></section><section className="section new-section"><div className="section-head"><div><span className="eyebrow">BARU DATANG</span><h2>New Arrival<span className="orange-dot">.</span></h2></div><Link href="/shop" className="text-link">Lihat semua <span>↗</span></Link></div><div className="product-grid">{newest.map(product => <ProductCard key={product.id} product={product} />)}</div></section><section className="closing"><span>✳</span><h2>Go outside. Be curious.</h2><p>Setiap hari adalah kesempatan untuk menemukan hal baru.</p><Link href="/shop" className="button dark-button">Lihat koleksi <span>↗</span></Link></section></main>;
}
