const money = value => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value);
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
import { invoiceNumber, orderNumber } from './order-number.js';
export { invoiceNumber } from './order-number.js';

export function orderEmailContent(order, { preview = false } = {}) {
  const number = invoiceNumber(order);
  const purchaseNumber = orderNumber(order);
  const items = order.items.map(item => `<tr><td style="padding:12px 0;border-bottom:1px solid #e7e5dd;color:#26342b">${escapeHtml(item.name)}</td><td style="padding:12px 8px;border-bottom:1px solid #e7e5dd;text-align:center;color:#26342b">${item.quantity}</td><td style="padding:12px 0;border-bottom:1px solid #e7e5dd;text-align:right;color:#26342b;white-space:nowrap">${money(item.price * item.quantity)}</td></tr>`).join('');
  const address = [order.address, `${order.city} ${order.postalCode}`].map(escapeHtml).join('<br>');
  return {
    subject: `${preview ? '[UJI COBA] ' : ''}Invoice ${number} | Pesanan Aira Daily diterima`,
    text: `${preview ? 'INI CONTOH EMAIL, BUKAN PESANAN NYATA.\n\n' : ''}Halo ${order.customerName},\n\nPesanan ${purchaseNumber} sudah kami terima. Invoice ${number} terlampir.\n\n${order.items.map(item => `${item.name} x${item.quantity} - ${money(item.price * item.quantity)}`).join('\n')}\n\nSubtotal produk: ${money(order.total)}\nOngkos kirim: akan dikonfirmasi\nTagihan akhir dan cara pembayaran akan kami konfirmasi. Pesanan ini belum dibayar.\n\nAlamat kirim:\n${order.address}\n${order.city} ${order.postalCode}\n\nTerima kasih,\nAira Daily`,
    html: `<!doctype html><html lang="id"><head><meta charset="utf-8"></head><body style="margin:0;background:#f5f3ec;font-family:Arial,sans-serif;color:#26342b"><div style="max-width:620px;margin:0 auto;padding:28px 16px">${preview ? '<div style="background:#f6eadb;padding:12px 18px;font-size:12px;font-weight:700;color:#764d2c">INI CONTOH EMAIL - BUKAN PESANAN NYATA</div>' : ''}<div style="background:#293c30;color:#fff;padding:24px 30px"><div style="font-size:24px;font-weight:700;letter-spacing:-1px">Aira Daily</div><div style="margin-top:6px;font-size:12px;color:#dce7d9">Konfirmasi pesanan</div></div><div style="background:#fff;padding:30px"><p style="margin:0 0 9px;font-size:12px;font-weight:700;color:#bb714b">PESANAN DITERIMA</p><h1 style="font-size:25px;line-height:1.25;margin:0 0 15px">Terima kasih, ${escapeHtml(order.customerName)}!</h1><p style="font-size:14px;line-height:1.65;margin:0 0 24px">Pesanan <strong>${purchaseNumber}</strong> sudah kami terima. Rincian invoice <strong>${number}</strong> terlampir sebagai PDF.</p><table role="presentation" style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr><th style="text-align:left;padding:10px 0;border-bottom:2px solid #293c30">Produk</th><th style="text-align:center;padding:10px 8px;border-bottom:2px solid #293c30">Jml</th><th style="text-align:right;padding:10px 0;border-bottom:2px solid #293c30">Jumlah</th></tr></thead><tbody>${items}</tbody></table><table role="presentation" style="width:100%;margin-top:18px;font-size:14px"><tr><td style="padding:6px 0">Subtotal produk</td><td style="text-align:right;font-weight:700">${money(order.total)}</td></tr><tr><td style="padding:6px 0">Ongkos kirim</td><td style="text-align:right">Akan dikonfirmasi</td></tr></table><div style="margin:24px 0;padding:16px;background:#f6eadb;font-size:13px;line-height:1.6;color:#66543b">Tagihan akhir dan cara pembayaran akan kami konfirmasi. Pesanan ini belum dibayar.</div><div style="font-size:13px;line-height:1.6"><strong>Dikirim ke</strong><br>${escapeHtml(order.customerName)}<br>${address}</div><p style="margin:28px 0 0;font-size:13px">Terima kasih,<br><strong>Tim Aira Daily</strong></p></div><div style="padding:18px;text-align:center;font-size:11px;color:#657365">Email ini dikirim otomatis untuk pesanan Anda di Aira Daily.</div></div></body></html>`,
  };
}
